# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20170619_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date completed'),
        ),
    ]
