# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todoitem_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'permissions': (('can_todo', 'set todo'),)},
        ),
    ]
