# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20170621_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='can_edit', to=settings.AUTH_USER_MODEL),
        ),
    ]
