# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20170621_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={},
        ),
    ]
