# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20170622_0708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'permissions': (('is_manager', 'manager perms'),)},
        ),
    ]
