# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20170623_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='log',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
